// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6re52a2kpLsQHjfUmPynoPVxvmpv7uTo',
    appId: '1:983865132947:android:c37a67254c82226f908a66',
    messagingSenderId: '983865132947',
    projectId: 'appli-cef3f',
    storageBucket: 'appli-cef3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqNXNATHBBzTGKqoULAFCB-eZZEfCjLQ',
    appId: '1:983865132947:ios:8170f6b53b67208e908a66',
    messagingSenderId: '983865132947',
    projectId: 'appli-cef3f',
    storageBucket: 'appli-cef3f.appspot.com',
    androidClientId: '983865132947-f4b1ietjb8oh1kidkv52fnmmkuc0te7g.apps.googleusercontent.com',
    iosClientId: '983865132947-c9in65he1bidfmdnshhjbhqdobf0ha0c.apps.googleusercontent.com',
    iosBundleId: 'wgcode.appli',
  );
}
